### PR TITLE
implementing 'convert to record TODOs'

### PR DESCRIPTION
**Pull request by omar-nassar**
Converting all below DTOs into records:

- ProductAggregate
- RecommendationSummary
- ReviewSummary
- ServiceAddresses

### CODE REVIEW

**Comment by mohamed-taman** [comment]
Thanks, @omar-nassar for your pull request, did you test these changes?

**Comment by omar-nassar** [comment]
Yes @mohamed-taman all test cases passed successfully.

**Comment by mohamed-taman** [comment]
@omar-nassar thanks.

**Comment by omar-nassar** [comment]
The `Jackson2ObjectMapperBuilderCustomizer` bean used since the java 14 records feature is not yet fully supported in Jackson, per this [https://github.com/FasterXML/jackson-future-ideas/issues/46](url).

Thanks!

**Comment by mohamed-taman** [comment]
I already have created HttpError in utilities project and annotated with some Jackson annotations to be serialized correctly to JSON, and liked your idea also, it doesn’t need any annotations over record.

**Comment by omar-nassar** [comment]
Thank you.

I have aimed to minimize the change needed later on (once Jackson support the records feature). At that time we have to remove the bean from one location only.

**Pull request merged**
