### PR TITLE
Use profile to activate dockerfile-maven-plugin based on the presence of a Dockerfile.

### PR DESCRIPTION
**Pull request by nickstolwijk**
By using profiles with activation you can activate certain plugins based on characteristics of the project instead of having properties in the pom.xml.

### CODE REVIEW

**Comment by mohamed-taman** [comment]
Reviewed and approved, with all conflicts resolved, and tested locally.

**Comment by nickstolwijk** [comment]
Do not change the phase, people don't expect "verify" to push an image. Just use the properties to skip install and deploy of the jar files: maven.install.skip and maven.deploy.skip.

**Comment by mohamed-taman** [comment]
Deploy gives me this error also
` Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project product-service: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter ->`

Do you know idea about it how to add `distributionManagement `element.

**Comment by nickstolwijk** [comment]
I don't think there is a valid repository where you can push the jar files. Normally this would be the company Nexus or Maven Central. Just skip the deploy with maven.deploy.skip.

**Comment by mohamed-taman** [comment]
But in this case of skipping deploy, the image will not be pushed to docker hub, as when I use verify goal.

**Comment by nickstolwijk** [comment]
The dockerfile-maven-plugin doesn't listen to the maven.deploy.skip property.

**Comment by mohamed-taman** [comment]
Thank you you are correct, but it will work as the following
`./mvnw clean deploy -Dmaven.install.skip -Dmaven.deploy.skip -f product-service`

1. Build an image.
2. Tag image.
3. Pushed it to my docker hub.

> I have externalized the image properties like maintainer, image prefix, and other user-specific properties to an external file called `store.properties`, it is a specific user (company) configuration and could be added to ignore list from your side.

**Pull request merged**
